// Generated by gencpp from file transportsysteem_pkg/TransportControlFeedback.msg
// DO NOT EDIT!


#ifndef TRANSPORTSYSTEEM_PKG_MESSAGE_TRANSPORTCONTROLFEEDBACK_H
#define TRANSPORTSYSTEEM_PKG_MESSAGE_TRANSPORTCONTROLFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace transportsysteem_pkg
{
template <class ContainerAllocator>
struct TransportControlFeedback_
{
  typedef TransportControlFeedback_<ContainerAllocator> Type;

  TransportControlFeedback_()
    {
    }
  TransportControlFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct TransportControlFeedback_

typedef ::transportsysteem_pkg::TransportControlFeedback_<std::allocator<void> > TransportControlFeedback;

typedef boost::shared_ptr< ::transportsysteem_pkg::TransportControlFeedback > TransportControlFeedbackPtr;
typedef boost::shared_ptr< ::transportsysteem_pkg::TransportControlFeedback const> TransportControlFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace transportsysteem_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "transportsysteem_pkg/TransportControlFeedback";
  }

  static const char* value(const ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"\n"
;
  }

  static const char* value(const ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TransportControlFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::transportsysteem_pkg::TransportControlFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TRANSPORTSYSTEEM_PKG_MESSAGE_TRANSPORTCONTROLFEEDBACK_H
