// Generated by gencpp from file transportsysteem_pkg/TransportControlGoal.msg
// DO NOT EDIT!


#ifndef TRANSPORTSYSTEEM_PKG_MESSAGE_TRANSPORTCONTROLGOAL_H
#define TRANSPORTSYSTEEM_PKG_MESSAGE_TRANSPORTCONTROLGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace transportsysteem_pkg
{
template <class ContainerAllocator>
struct TransportControlGoal_
{
  typedef TransportControlGoal_<ContainerAllocator> Type;

  TransportControlGoal_()
    : instruction()  {
    }
  TransportControlGoal_(const ContainerAllocator& _alloc)
    : instruction(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _instruction_type;
  _instruction_type instruction;





  typedef boost::shared_ptr< ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator> const> ConstPtr;

}; // struct TransportControlGoal_

typedef ::transportsysteem_pkg::TransportControlGoal_<std::allocator<void> > TransportControlGoal;

typedef boost::shared_ptr< ::transportsysteem_pkg::TransportControlGoal > TransportControlGoalPtr;
typedef boost::shared_ptr< ::transportsysteem_pkg::TransportControlGoal const> TransportControlGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator1> & lhs, const ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator2> & rhs)
{
  return lhs.instruction == rhs.instruction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator1> & lhs, const ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace transportsysteem_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4251c9c3720afa4138d846da006deeed";
  }

  static const char* value(const ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4251c9c3720afa41ULL;
  static const uint64_t static_value2 = 0x38d846da006deeedULL;
};

template<class ContainerAllocator>
struct DataType< ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "transportsysteem_pkg/TransportControlGoal";
  }

  static const char* value(const ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"string instruction\n"
;
  }

  static const char* value(const ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.instruction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TransportControlGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::transportsysteem_pkg::TransportControlGoal_<ContainerAllocator>& v)
  {
    s << indent << "instruction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.instruction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRANSPORTSYSTEEM_PKG_MESSAGE_TRANSPORTCONTROLGOAL_H
