(cl:defpackage robotarm-msg
  (:use )
  (:export
   "<MANIPULATORACTION>"
   "MANIPULATORACTION"
   "<MANIPULATORACTIONFEEDBACK>"
   "MANIPULATORACTIONFEEDBACK"
   "<MANIPULATORACTIONGOAL>"
   "MANIPULATORACTIONGOAL"
   "<MANIPULATORACTIONRESULT>"
   "MANIPULATORACTIONRESULT"
   "<MANIPULATORFEEDBACK>"
   "MANIPULATORFEEDBACK"
   "<MANIPULATORGOAL>"
   "MANIPULATORGOAL"
   "<MANIPULATORRESULT>"
   "MANIPULATORRESULT"
  ))

