; Auto-generated. Do not edit!


(cl:in-package robotarm-msg)


;//! \htmlinclude manipulatorResult.msg.html

(cl:defclass <manipulatorResult> (roslisp-msg-protocol:ros-message)
  ((tandenborstel_gesorteerd
    :reader tandenborstel_gesorteerd
    :initarg :tandenborstel_gesorteerd
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass manipulatorResult (<manipulatorResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <manipulatorResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'manipulatorResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robotarm-msg:<manipulatorResult> is deprecated: use robotarm-msg:manipulatorResult instead.")))

(cl:ensure-generic-function 'tandenborstel_gesorteerd-val :lambda-list '(m))
(cl:defmethod tandenborstel_gesorteerd-val ((m <manipulatorResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robotarm-msg:tandenborstel_gesorteerd-val is deprecated.  Use robotarm-msg:tandenborstel_gesorteerd instead.")
  (tandenborstel_gesorteerd m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <manipulatorResult>) ostream)
  "Serializes a message object of type '<manipulatorResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'tandenborstel_gesorteerd) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <manipulatorResult>) istream)
  "Deserializes a message object of type '<manipulatorResult>"
    (cl:setf (cl:slot-value msg 'tandenborstel_gesorteerd) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<manipulatorResult>)))
  "Returns string type for a message object of type '<manipulatorResult>"
  "robotarm/manipulatorResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'manipulatorResult)))
  "Returns string type for a message object of type 'manipulatorResult"
  "robotarm/manipulatorResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<manipulatorResult>)))
  "Returns md5sum for a message object of type '<manipulatorResult>"
  "2deff8970a603c7081936de17013c55a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'manipulatorResult)))
  "Returns md5sum for a message object of type 'manipulatorResult"
  "2deff8970a603c7081936de17013c55a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<manipulatorResult>)))
  "Returns full string definition for message of type '<manipulatorResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool tandenborstel_gesorteerd~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'manipulatorResult)))
  "Returns full string definition for message of type 'manipulatorResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool tandenborstel_gesorteerd~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <manipulatorResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <manipulatorResult>))
  "Converts a ROS message object to a list"
  (cl:list 'manipulatorResult
    (cl:cons ':tandenborstel_gesorteerd (tandenborstel_gesorteerd msg))
))
