; Auto-generated. Do not edit!


(cl:in-package transportsysteem_pkg-msg)


;//! \htmlinclude TransportControlFeedback.msg.html

(cl:defclass <TransportControlFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type cl:string
    :initform ""))
)

(cl:defclass TransportControlFeedback (<TransportControlFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TransportControlFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TransportControlFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name transportsysteem_pkg-msg:<TransportControlFeedback> is deprecated: use transportsysteem_pkg-msg:TransportControlFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <TransportControlFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader transportsysteem_pkg-msg:feedback-val is deprecated.  Use transportsysteem_pkg-msg:feedback instead.")
  (feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TransportControlFeedback>) ostream)
  "Serializes a message object of type '<TransportControlFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'feedback))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'feedback))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TransportControlFeedback>) istream)
  "Deserializes a message object of type '<TransportControlFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'feedback) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'feedback) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TransportControlFeedback>)))
  "Returns string type for a message object of type '<TransportControlFeedback>"
  "transportsysteem_pkg/TransportControlFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TransportControlFeedback)))
  "Returns string type for a message object of type 'TransportControlFeedback"
  "transportsysteem_pkg/TransportControlFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TransportControlFeedback>)))
  "Returns md5sum for a message object of type '<TransportControlFeedback>"
  "c14cdf907e5c7c7fd47292add15660f0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TransportControlFeedback)))
  "Returns md5sum for a message object of type 'TransportControlFeedback"
  "c14cdf907e5c7c7fd47292add15660f0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TransportControlFeedback>)))
  "Returns full string definition for message of type '<TransportControlFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%string feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TransportControlFeedback)))
  "Returns full string definition for message of type 'TransportControlFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%string feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TransportControlFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'feedback))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TransportControlFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TransportControlFeedback
    (cl:cons ':feedback (feedback msg))
))
