; Auto-generated. Do not edit!


(cl:in-package transportsysteem_pkg-msg)


;//! \htmlinclude TransportControlFeedback.msg.html

(cl:defclass <TransportControlFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TransportControlFeedback (<TransportControlFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TransportControlFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TransportControlFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name transportsysteem_pkg-msg:<TransportControlFeedback> is deprecated: use transportsysteem_pkg-msg:TransportControlFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TransportControlFeedback>) ostream)
  "Serializes a message object of type '<TransportControlFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TransportControlFeedback>) istream)
  "Deserializes a message object of type '<TransportControlFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TransportControlFeedback>)))
  "Returns string type for a message object of type '<TransportControlFeedback>"
  "transportsysteem_pkg/TransportControlFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TransportControlFeedback)))
  "Returns string type for a message object of type 'TransportControlFeedback"
  "transportsysteem_pkg/TransportControlFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TransportControlFeedback>)))
  "Returns md5sum for a message object of type '<TransportControlFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TransportControlFeedback)))
  "Returns md5sum for a message object of type 'TransportControlFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TransportControlFeedback>)))
  "Returns full string definition for message of type '<TransportControlFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TransportControlFeedback)))
  "Returns full string definition for message of type 'TransportControlFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TransportControlFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TransportControlFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TransportControlFeedback
))
