; Auto-generated. Do not edit!


(cl:in-package transportsysteem_pkg-msg)


;//! \htmlinclude TransportControlResult.msg.html

(cl:defclass <TransportControlResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass TransportControlResult (<TransportControlResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TransportControlResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TransportControlResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name transportsysteem_pkg-msg:<TransportControlResult> is deprecated: use transportsysteem_pkg-msg:TransportControlResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <TransportControlResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader transportsysteem_pkg-msg:result-val is deprecated.  Use transportsysteem_pkg-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TransportControlResult>) ostream)
  "Serializes a message object of type '<TransportControlResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'result) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TransportControlResult>) istream)
  "Deserializes a message object of type '<TransportControlResult>"
    (cl:setf (cl:slot-value msg 'result) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TransportControlResult>)))
  "Returns string type for a message object of type '<TransportControlResult>"
  "transportsysteem_pkg/TransportControlResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TransportControlResult)))
  "Returns string type for a message object of type 'TransportControlResult"
  "transportsysteem_pkg/TransportControlResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TransportControlResult>)))
  "Returns md5sum for a message object of type '<TransportControlResult>"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TransportControlResult)))
  "Returns md5sum for a message object of type 'TransportControlResult"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TransportControlResult>)))
  "Returns full string definition for message of type '<TransportControlResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TransportControlResult)))
  "Returns full string definition for message of type 'TransportControlResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TransportControlResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TransportControlResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TransportControlResult
    (cl:cons ':result (result msg))
))
