; Auto-generated. Do not edit!


(cl:in-package transportsysteem_pkg-msg)


;//! \htmlinclude TransportControlResult.msg.html

(cl:defclass <TransportControlResult> (roslisp-msg-protocol:ros-message)
  ((gelukt
    :reader gelukt
    :initarg :gelukt
    :type cl:boolean
    :initform cl:nil)
   (bericht
    :reader bericht
    :initarg :bericht
    :type cl:string
    :initform ""))
)

(cl:defclass TransportControlResult (<TransportControlResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TransportControlResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TransportControlResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name transportsysteem_pkg-msg:<TransportControlResult> is deprecated: use transportsysteem_pkg-msg:TransportControlResult instead.")))

(cl:ensure-generic-function 'gelukt-val :lambda-list '(m))
(cl:defmethod gelukt-val ((m <TransportControlResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader transportsysteem_pkg-msg:gelukt-val is deprecated.  Use transportsysteem_pkg-msg:gelukt instead.")
  (gelukt m))

(cl:ensure-generic-function 'bericht-val :lambda-list '(m))
(cl:defmethod bericht-val ((m <TransportControlResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader transportsysteem_pkg-msg:bericht-val is deprecated.  Use transportsysteem_pkg-msg:bericht instead.")
  (bericht m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TransportControlResult>) ostream)
  "Serializes a message object of type '<TransportControlResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'gelukt) 1 0)) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'bericht))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'bericht))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TransportControlResult>) istream)
  "Deserializes a message object of type '<TransportControlResult>"
    (cl:setf (cl:slot-value msg 'gelukt) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'bericht) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'bericht) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TransportControlResult>)))
  "Returns string type for a message object of type '<TransportControlResult>"
  "transportsysteem_pkg/TransportControlResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TransportControlResult)))
  "Returns string type for a message object of type 'TransportControlResult"
  "transportsysteem_pkg/TransportControlResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TransportControlResult>)))
  "Returns md5sum for a message object of type '<TransportControlResult>"
  "a8b436ede0ab289199df25c7e6703001")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TransportControlResult)))
  "Returns md5sum for a message object of type 'TransportControlResult"
  "a8b436ede0ab289199df25c7e6703001")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TransportControlResult>)))
  "Returns full string definition for message of type '<TransportControlResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool gelukt~%string bericht~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TransportControlResult)))
  "Returns full string definition for message of type 'TransportControlResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool gelukt~%string bericht~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TransportControlResult>))
  (cl:+ 0
     1
     4 (cl:length (cl:slot-value msg 'bericht))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TransportControlResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TransportControlResult
    (cl:cons ':gelukt (gelukt msg))
    (cl:cons ':bericht (bericht msg))
))
