// Auto-generated. Do not edit!

// (in-package transportsysteem_pkg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class TransportControlResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.gelukt = null;
      this.bericht = null;
    }
    else {
      if (initObj.hasOwnProperty('gelukt')) {
        this.gelukt = initObj.gelukt
      }
      else {
        this.gelukt = false;
      }
      if (initObj.hasOwnProperty('bericht')) {
        this.bericht = initObj.bericht
      }
      else {
        this.bericht = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TransportControlResult
    // Serialize message field [gelukt]
    bufferOffset = _serializer.bool(obj.gelukt, buffer, bufferOffset);
    // Serialize message field [bericht]
    bufferOffset = _serializer.string(obj.bericht, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TransportControlResult
    let len;
    let data = new TransportControlResult(null);
    // Deserialize message field [gelukt]
    data.gelukt = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [bericht]
    data.bericht = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.bericht.length;
    return length + 5;
  }

  static datatype() {
    // Returns string type for a message object
    return 'transportsysteem_pkg/TransportControlResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'a8b436ede0ab289199df25c7e6703001';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result
    bool gelukt
    string bericht
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TransportControlResult(null);
    if (msg.gelukt !== undefined) {
      resolved.gelukt = msg.gelukt;
    }
    else {
      resolved.gelukt = false
    }

    if (msg.bericht !== undefined) {
      resolved.bericht = msg.bericht;
    }
    else {
      resolved.bericht = ''
    }

    return resolved;
    }
};

module.exports = TransportControlResult;
