; Auto-generated. Do not edit!


(cl:in-package transportsysteem_pkg-msg)


;//! \htmlinclude SystemControlGoal.msg.html

(cl:defclass <SystemControlGoal> (roslisp-msg-protocol:ros-message)
  ((instruction
    :reader instruction
    :initarg :instruction
    :type cl:string
    :initform ""))
)

(cl:defclass SystemControlGoal (<SystemControlGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SystemControlGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SystemControlGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name transportsysteem_pkg-msg:<SystemControlGoal> is deprecated: use transportsysteem_pkg-msg:SystemControlGoal instead.")))

(cl:ensure-generic-function 'instruction-val :lambda-list '(m))
(cl:defmethod instruction-val ((m <SystemControlGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader transportsysteem_pkg-msg:instruction-val is deprecated.  Use transportsysteem_pkg-msg:instruction instead.")
  (instruction m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SystemControlGoal>) ostream)
  "Serializes a message object of type '<SystemControlGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'instruction))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'instruction))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SystemControlGoal>) istream)
  "Deserializes a message object of type '<SystemControlGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'instruction) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'instruction) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SystemControlGoal>)))
  "Returns string type for a message object of type '<SystemControlGoal>"
  "transportsysteem_pkg/SystemControlGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SystemControlGoal)))
  "Returns string type for a message object of type 'SystemControlGoal"
  "transportsysteem_pkg/SystemControlGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SystemControlGoal>)))
  "Returns md5sum for a message object of type '<SystemControlGoal>"
  "4251c9c3720afa4138d846da006deeed")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SystemControlGoal)))
  "Returns md5sum for a message object of type 'SystemControlGoal"
  "4251c9c3720afa4138d846da006deeed")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SystemControlGoal>)))
  "Returns full string definition for message of type '<SystemControlGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string instruction~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SystemControlGoal)))
  "Returns full string definition for message of type 'SystemControlGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string instruction~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SystemControlGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'instruction))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SystemControlGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SystemControlGoal
    (cl:cons ':instruction (instruction msg))
))
