// Auto-generated. Do not edit!

// (in-package robotarm.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class manipulatorFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.tandenborstel_opgepakt = null;
    }
    else {
      if (initObj.hasOwnProperty('tandenborstel_opgepakt')) {
        this.tandenborstel_opgepakt = initObj.tandenborstel_opgepakt
      }
      else {
        this.tandenborstel_opgepakt = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type manipulatorFeedback
    // Serialize message field [tandenborstel_opgepakt]
    bufferOffset = _serializer.bool(obj.tandenborstel_opgepakt, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type manipulatorFeedback
    let len;
    let data = new manipulatorFeedback(null);
    // Deserialize message field [tandenborstel_opgepakt]
    data.tandenborstel_opgepakt = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robotarm/manipulatorFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '13244125ac2eb6e745592ab638bae6b5';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback
    bool tandenborstel_opgepakt
    
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new manipulatorFeedback(null);
    if (msg.tandenborstel_opgepakt !== undefined) {
      resolved.tandenborstel_opgepakt = msg.tandenborstel_opgepakt;
    }
    else {
      resolved.tandenborstel_opgepakt = false
    }

    return resolved;
    }
};

module.exports = manipulatorFeedback;
