// Auto-generated. Do not edit!

// (in-package robotarm.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class manipulatorGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.manipulator_start = null;
    }
    else {
      if (initObj.hasOwnProperty('manipulator_start')) {
        this.manipulator_start = initObj.manipulator_start
      }
      else {
        this.manipulator_start = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type manipulatorGoal
    // Serialize message field [manipulator_start]
    bufferOffset = _serializer.bool(obj.manipulator_start, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type manipulatorGoal
    let len;
    let data = new manipulatorGoal(null);
    // Deserialize message field [manipulator_start]
    data.manipulator_start = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robotarm/manipulatorGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3868a330ea8e060554882c30a838b6a7';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    bool manipulator_start
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new manipulatorGoal(null);
    if (msg.manipulator_start !== undefined) {
      resolved.manipulator_start = msg.manipulator_start;
    }
    else {
      resolved.manipulator_start = false
    }

    return resolved;
    }
};

module.exports = manipulatorGoal;
