// Auto-generated. Do not edit!

// (in-package robotarm.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class manipulatorResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.tandenborstel_gesorteerd = null;
    }
    else {
      if (initObj.hasOwnProperty('tandenborstel_gesorteerd')) {
        this.tandenborstel_gesorteerd = initObj.tandenborstel_gesorteerd
      }
      else {
        this.tandenborstel_gesorteerd = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type manipulatorResult
    // Serialize message field [tandenborstel_gesorteerd]
    bufferOffset = _serializer.bool(obj.tandenborstel_gesorteerd, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type manipulatorResult
    let len;
    let data = new manipulatorResult(null);
    // Deserialize message field [tandenborstel_gesorteerd]
    data.tandenborstel_gesorteerd = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robotarm/manipulatorResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2deff8970a603c7081936de17013c55a';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result
    bool tandenborstel_gesorteerd
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new manipulatorResult(null);
    if (msg.tandenborstel_gesorteerd !== undefined) {
      resolved.tandenborstel_gesorteerd = msg.tandenborstel_gesorteerd;
    }
    else {
      resolved.tandenborstel_gesorteerd = false
    }

    return resolved;
    }
};

module.exports = manipulatorResult;
