// Generated by gencpp from file transportsysteem_pkg/ControlStateResponse.msg
// DO NOT EDIT!


#ifndef TRANSPORTSYSTEEM_PKG_MESSAGE_CONTROLSTATERESPONSE_H
#define TRANSPORTSYSTEEM_PKG_MESSAGE_CONTROLSTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace transportsysteem_pkg
{
template <class ContainerAllocator>
struct ControlStateResponse_
{
  typedef ControlStateResponse_<ContainerAllocator> Type;

  ControlStateResponse_()
    : success(false)  {
    }
  ControlStateResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ControlStateResponse_

typedef ::transportsysteem_pkg::ControlStateResponse_<std::allocator<void> > ControlStateResponse;

typedef boost::shared_ptr< ::transportsysteem_pkg::ControlStateResponse > ControlStateResponsePtr;
typedef boost::shared_ptr< ::transportsysteem_pkg::ControlStateResponse const> ControlStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator1> & lhs, const ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator1> & lhs, const ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace transportsysteem_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "transportsysteem_pkg/ControlStateResponse";
  }

  static const char* value(const ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response: Whether the state transition was successfully executed\n"
"bool success\n"
;
  }

  static const char* value(const ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::transportsysteem_pkg::ControlStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRANSPORTSYSTEEM_PKG_MESSAGE_CONTROLSTATERESPONSE_H
