// Generated by gencpp from file transportsysteem_pkg/ControlState.msg
// DO NOT EDIT!


#ifndef TRANSPORTSYSTEEM_PKG_MESSAGE_CONTROLSTATE_H
#define TRANSPORTSYSTEEM_PKG_MESSAGE_CONTROLSTATE_H

#include <ros/service_traits.h>


#include <transportsysteem_pkg/ControlStateRequest.h>
#include <transportsysteem_pkg/ControlStateResponse.h>


namespace transportsysteem_pkg
{

struct ControlState
{

typedef ControlStateRequest Request;
typedef ControlStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ControlState
} // namespace transportsysteem_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::transportsysteem_pkg::ControlState > {
  static const char* value()
  {
    return "ba7d0f17aa81fce463f555ebbb18949e";
  }

  static const char* value(const ::transportsysteem_pkg::ControlState&) { return value(); }
};

template<>
struct DataType< ::transportsysteem_pkg::ControlState > {
  static const char* value()
  {
    return "transportsysteem_pkg/ControlState";
  }

  static const char* value(const ::transportsysteem_pkg::ControlState&) { return value(); }
};


// service_traits::MD5Sum< ::transportsysteem_pkg::ControlStateRequest> should match
// service_traits::MD5Sum< ::transportsysteem_pkg::ControlState >
template<>
struct MD5Sum< ::transportsysteem_pkg::ControlStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::transportsysteem_pkg::ControlState >::value();
  }
  static const char* value(const ::transportsysteem_pkg::ControlStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::transportsysteem_pkg::ControlStateRequest> should match
// service_traits::DataType< ::transportsysteem_pkg::ControlState >
template<>
struct DataType< ::transportsysteem_pkg::ControlStateRequest>
{
  static const char* value()
  {
    return DataType< ::transportsysteem_pkg::ControlState >::value();
  }
  static const char* value(const ::transportsysteem_pkg::ControlStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::transportsysteem_pkg::ControlStateResponse> should match
// service_traits::MD5Sum< ::transportsysteem_pkg::ControlState >
template<>
struct MD5Sum< ::transportsysteem_pkg::ControlStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::transportsysteem_pkg::ControlState >::value();
  }
  static const char* value(const ::transportsysteem_pkg::ControlStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::transportsysteem_pkg::ControlStateResponse> should match
// service_traits::DataType< ::transportsysteem_pkg::ControlState >
template<>
struct DataType< ::transportsysteem_pkg::ControlStateResponse>
{
  static const char* value()
  {
    return DataType< ::transportsysteem_pkg::ControlState >::value();
  }
  static const char* value(const ::transportsysteem_pkg::ControlStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRANSPORTSYSTEEM_PKG_MESSAGE_CONTROLSTATE_H
