// Generated by gencpp from file transportsysteem_pkg/ControlStateRequest.msg
// DO NOT EDIT!


#ifndef TRANSPORTSYSTEEM_PKG_MESSAGE_CONTROLSTATEREQUEST_H
#define TRANSPORTSYSTEEM_PKG_MESSAGE_CONTROLSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace transportsysteem_pkg
{
template <class ContainerAllocator>
struct ControlStateRequest_
{
  typedef ControlStateRequest_<ContainerAllocator> Type;

  ControlStateRequest_()
    : state()  {
    }
  ControlStateRequest_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ControlStateRequest_

typedef ::transportsysteem_pkg::ControlStateRequest_<std::allocator<void> > ControlStateRequest;

typedef boost::shared_ptr< ::transportsysteem_pkg::ControlStateRequest > ControlStateRequestPtr;
typedef boost::shared_ptr< ::transportsysteem_pkg::ControlStateRequest const> ControlStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator1> & lhs, const ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator1> & lhs, const ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace transportsysteem_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf6d3a99f0fbeb66ULL;
  static const uint64_t static_value2 = 0xd3248fa4b3e675fbULL;
};

template<class ContainerAllocator>
struct DataType< ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "transportsysteem_pkg/ControlStateRequest";
  }

  static const char* value(const ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request: The state the system should go to (\"start\", \"wait\", \"dump\")\n"
"string state\n"
;
  }

  static const char* value(const ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::transportsysteem_pkg::ControlStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRANSPORTSYSTEEM_PKG_MESSAGE_CONTROLSTATEREQUEST_H
