// Generated by gencpp from file transportsysteem_pkg/SystemControl.msg
// DO NOT EDIT!


#ifndef TRANSPORTSYSTEEM_PKG_MESSAGE_SYSTEMCONTROL_H
#define TRANSPORTSYSTEEM_PKG_MESSAGE_SYSTEMCONTROL_H

#include <ros/service_traits.h>


#include <transportsysteem_pkg/SystemControlRequest.h>
#include <transportsysteem_pkg/SystemControlResponse.h>


namespace transportsysteem_pkg
{

struct SystemControl
{

typedef SystemControlRequest Request;
typedef SystemControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SystemControl
} // namespace transportsysteem_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::transportsysteem_pkg::SystemControl > {
  static const char* value()
  {
    return "acc3bbca6f8e73aa0ef1136aa9bdba5b";
  }

  static const char* value(const ::transportsysteem_pkg::SystemControl&) { return value(); }
};

template<>
struct DataType< ::transportsysteem_pkg::SystemControl > {
  static const char* value()
  {
    return "transportsysteem_pkg/SystemControl";
  }

  static const char* value(const ::transportsysteem_pkg::SystemControl&) { return value(); }
};


// service_traits::MD5Sum< ::transportsysteem_pkg::SystemControlRequest> should match
// service_traits::MD5Sum< ::transportsysteem_pkg::SystemControl >
template<>
struct MD5Sum< ::transportsysteem_pkg::SystemControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::transportsysteem_pkg::SystemControl >::value();
  }
  static const char* value(const ::transportsysteem_pkg::SystemControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::transportsysteem_pkg::SystemControlRequest> should match
// service_traits::DataType< ::transportsysteem_pkg::SystemControl >
template<>
struct DataType< ::transportsysteem_pkg::SystemControlRequest>
{
  static const char* value()
  {
    return DataType< ::transportsysteem_pkg::SystemControl >::value();
  }
  static const char* value(const ::transportsysteem_pkg::SystemControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::transportsysteem_pkg::SystemControlResponse> should match
// service_traits::MD5Sum< ::transportsysteem_pkg::SystemControl >
template<>
struct MD5Sum< ::transportsysteem_pkg::SystemControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::transportsysteem_pkg::SystemControl >::value();
  }
  static const char* value(const ::transportsysteem_pkg::SystemControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::transportsysteem_pkg::SystemControlResponse> should match
// service_traits::DataType< ::transportsysteem_pkg::SystemControl >
template<>
struct DataType< ::transportsysteem_pkg::SystemControlResponse>
{
  static const char* value()
  {
    return DataType< ::transportsysteem_pkg::SystemControl >::value();
  }
  static const char* value(const ::transportsysteem_pkg::SystemControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRANSPORTSYSTEEM_PKG_MESSAGE_SYSTEMCONTROL_H
