// Generated by gencpp from file transportsysteem_pkg/SystemControlResponse.msg
// DO NOT EDIT!


#ifndef TRANSPORTSYSTEEM_PKG_MESSAGE_SYSTEMCONTROLRESPONSE_H
#define TRANSPORTSYSTEEM_PKG_MESSAGE_SYSTEMCONTROLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace transportsysteem_pkg
{
template <class ContainerAllocator>
struct SystemControlResponse_
{
  typedef SystemControlResponse_<ContainerAllocator> Type;

  SystemControlResponse_()
    : result(false)  {
    }
  SystemControlResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SystemControlResponse_

typedef ::transportsysteem_pkg::SystemControlResponse_<std::allocator<void> > SystemControlResponse;

typedef boost::shared_ptr< ::transportsysteem_pkg::SystemControlResponse > SystemControlResponsePtr;
typedef boost::shared_ptr< ::transportsysteem_pkg::SystemControlResponse const> SystemControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator1> & lhs, const ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator1> & lhs, const ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace transportsysteem_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "transportsysteem_pkg/SystemControlResponse";
  }

  static const char* value(const ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response: Whether the state transition was successfully executed\n"
"bool result\n"
"\n"
;
  }

  static const char* value(const ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::transportsysteem_pkg::SystemControlResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRANSPORTSYSTEEM_PKG_MESSAGE_SYSTEMCONTROLRESPONSE_H
