// Generated by gencpp from file robotarm/manipulatorResult.msg
// DO NOT EDIT!


#ifndef ROBOTARM_MESSAGE_MANIPULATORRESULT_H
#define ROBOTARM_MESSAGE_MANIPULATORRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotarm
{
template <class ContainerAllocator>
struct manipulatorResult_
{
  typedef manipulatorResult_<ContainerAllocator> Type;

  manipulatorResult_()
    : tandenborstel_gesorteerd(false)  {
    }
  manipulatorResult_(const ContainerAllocator& _alloc)
    : tandenborstel_gesorteerd(false)  {
  (void)_alloc;
    }



   typedef uint8_t _tandenborstel_gesorteerd_type;
  _tandenborstel_gesorteerd_type tandenborstel_gesorteerd;





  typedef boost::shared_ptr< ::robotarm::manipulatorResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotarm::manipulatorResult_<ContainerAllocator> const> ConstPtr;

}; // struct manipulatorResult_

typedef ::robotarm::manipulatorResult_<std::allocator<void> > manipulatorResult;

typedef boost::shared_ptr< ::robotarm::manipulatorResult > manipulatorResultPtr;
typedef boost::shared_ptr< ::robotarm::manipulatorResult const> manipulatorResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotarm::manipulatorResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotarm::manipulatorResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotarm::manipulatorResult_<ContainerAllocator1> & lhs, const ::robotarm::manipulatorResult_<ContainerAllocator2> & rhs)
{
  return lhs.tandenborstel_gesorteerd == rhs.tandenborstel_gesorteerd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotarm::manipulatorResult_<ContainerAllocator1> & lhs, const ::robotarm::manipulatorResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotarm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robotarm::manipulatorResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotarm::manipulatorResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarm::manipulatorResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarm::manipulatorResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarm::manipulatorResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarm::manipulatorResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotarm::manipulatorResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2deff8970a603c7081936de17013c55a";
  }

  static const char* value(const ::robotarm::manipulatorResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2deff8970a603c70ULL;
  static const uint64_t static_value2 = 0x81936de17013c55aULL;
};

template<class ContainerAllocator>
struct DataType< ::robotarm::manipulatorResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotarm/manipulatorResult";
  }

  static const char* value(const ::robotarm::manipulatorResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotarm::manipulatorResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"bool tandenborstel_gesorteerd\n"
;
  }

  static const char* value(const ::robotarm::manipulatorResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotarm::manipulatorResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tandenborstel_gesorteerd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct manipulatorResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotarm::manipulatorResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotarm::manipulatorResult_<ContainerAllocator>& v)
  {
    s << indent << "tandenborstel_gesorteerd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tandenborstel_gesorteerd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTARM_MESSAGE_MANIPULATORRESULT_H
