; Auto-generated. Do not edit!


(cl:in-package robotarm-msg)


;//! \htmlinclude manipulatorGoal.msg.html

(cl:defclass <manipulatorGoal> (roslisp-msg-protocol:ros-message)
  ((manipulator_start
    :reader manipulator_start
    :initarg :manipulator_start
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass manipulatorGoal (<manipulatorGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <manipulatorGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'manipulatorGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robotarm-msg:<manipulatorGoal> is deprecated: use robotarm-msg:manipulatorGoal instead.")))

(cl:ensure-generic-function 'manipulator_start-val :lambda-list '(m))
(cl:defmethod manipulator_start-val ((m <manipulatorGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robotarm-msg:manipulator_start-val is deprecated.  Use robotarm-msg:manipulator_start instead.")
  (manipulator_start m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <manipulatorGoal>) ostream)
  "Serializes a message object of type '<manipulatorGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'manipulator_start) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <manipulatorGoal>) istream)
  "Deserializes a message object of type '<manipulatorGoal>"
    (cl:setf (cl:slot-value msg 'manipulator_start) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<manipulatorGoal>)))
  "Returns string type for a message object of type '<manipulatorGoal>"
  "robotarm/manipulatorGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'manipulatorGoal)))
  "Returns string type for a message object of type 'manipulatorGoal"
  "robotarm/manipulatorGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<manipulatorGoal>)))
  "Returns md5sum for a message object of type '<manipulatorGoal>"
  "3868a330ea8e060554882c30a838b6a7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'manipulatorGoal)))
  "Returns md5sum for a message object of type 'manipulatorGoal"
  "3868a330ea8e060554882c30a838b6a7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<manipulatorGoal>)))
  "Returns full string definition for message of type '<manipulatorGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%bool manipulator_start~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'manipulatorGoal)))
  "Returns full string definition for message of type 'manipulatorGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%bool manipulator_start~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <manipulatorGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <manipulatorGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'manipulatorGoal
    (cl:cons ':manipulator_start (manipulator_start msg))
))
